# Form implementation generated from reading ui file 'settingsDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(302, 241)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 140, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 271, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.RowWrapPolicy.DontWrapRows)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.waveformLengthLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.waveformLengthLabel.setObjectName("waveformLengthLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.waveformLengthLabel)
        self.waveformLengthLineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waveformLengthLineEdit.sizePolicy().hasHeightForWidth())
        self.waveformLengthLineEdit.setSizePolicy(sizePolicy)
        self.waveformLengthLineEdit.setObjectName("waveformLengthLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.waveformLengthLineEdit)
        self.alignAtLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.alignAtLabel.setObjectName("alignAtLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.alignAtLabel)
        self.alignAtComboBox = QtWidgets.QComboBox(parent=self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignAtComboBox.sizePolicy().hasHeightForWidth())
        self.alignAtComboBox.setSizePolicy(sizePolicy)
        self.alignAtComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.alignAtComboBox.setMinimumContentsLength(20)
        self.alignAtComboBox.setObjectName("alignAtComboBox")
        self.alignAtComboBox.addItem("")
        self.alignAtComboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.alignAtComboBox)
        self.deadTimeSamplesLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.deadTimeSamplesLabel.setObjectName("deadTimeSamplesLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.deadTimeSamplesLabel)
        self.deadTimeSamplesLineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.deadTimeSamplesLineEdit.setObjectName("deadTimeSamplesLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.deadTimeSamplesLineEdit)
        self.fractionPreAlignLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.fractionPreAlignLabel.setObjectName("fractionPreAlignLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.fractionPreAlignLabel)
        self.fractionPreAlignLineEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.fractionPreAlignLineEdit.setObjectName("fractionPreAlignLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.fractionPreAlignLineEdit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Advanced Settings"))
        self.label.setText(_translate("Dialog", "Waveform Settings"))
        self.waveformLengthLabel.setText(_translate("Dialog", "Length (samples)"))
        self.waveformLengthLineEdit.setText(_translate("Dialog", "32"))
        self.alignAtLabel.setText(_translate("Dialog", "Align at"))
        self.alignAtComboBox.setItemText(0, _translate("Dialog", "local maxima"))
        self.alignAtComboBox.setItemText(1, _translate("Dialog", "threshold crossing"))
        self.deadTimeSamplesLabel.setText(_translate("Dialog", "Dead time (samples)"))
        self.deadTimeSamplesLineEdit.setText(_translate("Dialog", "30"))
        self.fractionPreAlignLabel.setText(_translate("Dialog", "Fraction pre-align"))
        self.fractionPreAlignLineEdit.setText(_translate("Dialog", "0.4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
